name: Go Build/Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GOFLAGS: -buildvcs=false

jobs:
  build:
    runs-on: [ self-hosted, Linux, X64, Docker ]
    container: golang:1.22-bookworm
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'go'
          fetch-depth: '2'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Coverage
        run: go test -cover ./...

      - name: Convert status to uppercase
        if: always()
        id: status
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ job.status }}

      - name: Create Slack description from PR
        if: always() && github.event_name == 'pull_request'
        id: pr
        run: |
          echo 'description<<EOF' >> $GITHUB_OUTPUT
          echo *${{ github.event.pull_request.title }}* >> $GITHUB_OUTPUT
          git show -s --format=%B ${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Post build result to Slack
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "GitHub Action <https://github.com/${{ github.repository }}|${{ github.repository }}> ${{ github.workflow }}: *${{ steps.status.outputs.uppercase }}*",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && '#22bb33' || '#bb2124' }}",
                  "blocks": [
                    {   
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": ${{ toJson(steps.pr.outputs.description || github.event.head_commit.message) }}
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "View PR or commit"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "View"
                        },
                        "value": "click_me_123",
                        "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                        "action_id": "button-action"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "View build logs"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "View"
                        },
                        "value": "click_me_123",
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
